var DEFINE = {};

DEFINE.GameState = {
	GAME_PREPARE:'prepare',
	GAME_START:'start',
	GAME_OVER:'over',
};

DEFINE.ActionType = {
	ACTION_CHUPAI: 1,
	ACTION_MOPAI: 2,
	ACTION_PENG: 3,
	ACTION_GANG: 4,
	ACTION_HU: 5,
	ACTION_DANCHI: 6,
	ACTION_CHI: 7,
	ACTION_KAIJINLONG: 8,
	ACTION_GUO: 9,
	ACTION_STAR: 10,
	ACTION_SCORE: 11,
	ACTION_DIPAI: 12,
};

module.exports = DEFINE;